backend:
  name: git-gateway
  branch: main

media_folder: "image"
public_folder: "/image"

collections:
  - name: "work"
    label: "My Work"
    folder: "content/work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Media", name: "media", widget: "file" }